### ETL - World Happiness Report

In [1]:
# Dependencies
import pandas as pd
import os
import glob

In [2]:
# Create loop to open each csv file
path = 'Resources'
filenames = glob.glob(path + "/*.csv")

d = {}

for filename in filenames:
    d[filename] = pd.read_csv(filename)
    print(filename)

Resources/2019.csv
Resources/2018.csv
Resources/2015.csv
Resources/2016.csv
Resources/2017.csv

### 2015

In [3]:
# Save each df to unique variable
df_2015 = d['Resources/2015.csv']
df_2015.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

In [26]:
new_df_2015 = df_2015[['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)', 
                       'Health (Life Expectancy)','Freedom', 'Trust (Government Corruption)', 'Generosity']].copy()
new_df_2015.rename(columns = {'Country': "country", 'Region': "region", 'Happiness Rank': "happiness rank", 
                             'Happiness Score': "happiness score", 'Economy (GDP per Capita)': "GDP",
                             'Health (Life Expectancy)': "health - life expectancy", 'Freedom':"freedom",
                             'Trust (Government Corruption)': "trust (govt corruption)", 'Generosity': "generosity"}, inplace=True)
new_df_2015

,country,region,happiness rank,happiness score,GDP,health - life expectancy,freedom,trust (govt corruption),generosity
0,Switzerland,Western Europe,1,7.587,1.39651,0.94143,0.66557,0.41978,0.29678
1,Iceland,Western Europe,2,7.561,1.30232,0.94784,0.62877,0.14145,0.43630
2,Denmark,Western Europe,3,7.527,1.32548,0.87464,0.64938,0.48357,0.34139
3,Norway,Western Europe,4,7.522,1.45900,0.88521,0.66973,0.36503,0.34699
4,Canada,North America,5,7.427,1.32629,0.90563,0.63297,0.32957,0.45811
...,...,...,...,...,...,...,...,...,...
153,Rwanda,Sub-Saharan Africa,154,3.465,0.22208,0.42864,0.59201,0.55191,0.22628
154,Benin,Sub-Saharan Africa,155,3.340,0.28665,0.31910,0.48450,0.08010,0.18260
155,Syria,Middle East and Northern Africa,156,3.006,0.66320,0.72193,0.15684,0.18906,0.47179
156,Burundi,Sub-Saharan Africa,157,2.905,0.01530,0.22396,0.11850,0.10062,0.19727
157,Togo,Sub-Saharan Africa,158,2.839,0.20868,0.28443,0.36453,0.10731,0.16681

### 2016

In [6]:
df_2016 = d['Resources/2016.csv']
df_2016.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

In [28]:
new_df_2016 = df_2016[['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)', 
                       'Health (Life Expectancy)','Freedom', 'Trust (Government Corruption)', 'Generosity']].copy()
new_df_2016.rename(columns = {'Country': "country", 'Region': "region", 'Happiness Rank': "happiness rank", 
                             'Happiness Score': "happiness score", 'Economy (GDP per Capita)': "GDP",
                             'Health (Life Expectancy)': "health - life expectancy", 'Freedom':"freedom",
                             'Trust (Government Corruption)': "trust (govt corruption)", 'Generosity': "generosity"}, inplace=True)
new_df_2016

,country,region,happiness rank,happiness score,GDP,health - life expectancy,freedom,trust (govt corruption),generosity
0,Denmark,Western Europe,1,7.526,1.44178,0.79504,0.57941,0.44453,0.36171
1,Switzerland,Western Europe,2,7.509,1.52733,0.86303,0.58557,0.41203,0.28083
2,Iceland,Western Europe,3,7.501,1.42666,0.86733,0.56624,0.14975,0.47678
3,Norway,Western Europe,4,7.498,1.57744,0.79579,0.59609,0.35776,0.37895
4,Finland,Western Europe,5,7.413,1.40598,0.81091,0.57104,0.41004,0.25492
...,...,...,...,...,...,...,...,...,...
152,Benin,Sub-Saharan Africa,153,3.484,0.39499,0.21028,0.39747,0.06681,0.20180
153,Afghanistan,Southern Asia,154,3.360,0.38227,0.17344,0.16430,0.07112,0.31268
154,Togo,Sub-Saharan Africa,155,3.303,0.28123,0.24811,0.34678,0.11587,0.17517
155,Syria,Middle East and Northern Africa,156,3.069,0.74719,0.62994,0.06912,0.17233,0.48397
156,Burundi,Sub-Saharan Africa,157,2.905,0.06831,0.15747,0.04320,0.09419,0.20290

### 2017

In [33]:
df_2017 = d['Resources/2017.csv']
df_2017.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual'],
      dtype='object')

In [30]:
new_df_2017 = df_2017[['Country', 'Happiness.Rank', 'Happiness.Score', 'Economy..GDP.per.Capita.', 
                       'Health..Life.Expectancy.','Freedom', 'Trust..Government.Corruption.', 'Generosity']].copy()
new_df_2017.rename(columns = {'Country': "country", 'Happiness.Rank': "happiness rank", 
                             'Happiness.Score': "happiness score", 'Economy..GDP.per.Capita.': "GDP",
                             'Health..Life.Expectancy.': "health - life expectancy", 'Freedom':"freedom",
                             'Trust..Government.Corruption.': "trust (govt corruption)", 'Generosity': "generosity"}, inplace=True)
new_df_2017

,country,happiness rank,happiness score,GDP,health - life expectancy,freedom,trust (govt corruption),generosity
0,Norway,1,7.537,1.616463,0.796667,0.635423,0.315964,0.362012
1,Denmark,2,7.522,1.482383,0.792566,0.626007,0.400770,0.355280
2,Iceland,3,7.504,1.480633,0.833552,0.627163,0.153527,0.475540
3,Switzerland,4,7.494,1.564980,0.858131,0.620071,0.367007,0.290549
4,Finland,5,7.469,1.443572,0.809158,0.617951,0.382612,0.245483
...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,0.368746,0.326425,0.581844,0.455220,0.252756
151,Syria,152,3.462,0.777153,0.500533,0.081539,0.151347,0.493664
152,Tanzania,153,3.349,0.511136,0.364509,0.390018,0.066035,0.354256
153,Burundi,154,2.905,0.091623,0.151611,0.059901,0.084148,0.204435
154,Central African Republic,155,2.693,0.000000,0.018773,0.270842,0.056565,0.280876

### 2018

In [32]:
df_2018 = d['Resources/2018.csv']
df_2018.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [31]:
new_df_2018 = df_2018[['Country or region', 'Overall rank', 'Score', 'GDP per capita', 'Healthy life expectancy',
                      'Freedom to make life choices', 'Perceptions of corruption', 'Generosity']].copy()
new_df_2018.rename(columns = {'Country or region': "country", 'Overall rank': "happiness rank", 
                             'Score': "happiness score", 'GDP per capita': "GDP",
                             'Healthy life expectancy': "health - life expectancy", 'Freedom to make life choices':"freedom",
                             'Perceptions of corruption': "trust (govt corruption)", 'Generosity': "generosity"}, inplace=True)
new_df_2018

,country,happiness rank,happiness score,GDP,health - life expectancy,freedom,trust (govt corruption),generosity
0,Finland,1,7.632,1.305,0.874,0.681,0.393,0.202
1,Norway,2,7.594,1.456,0.861,0.686,0.340,0.286
2,Denmark,3,7.555,1.351,0.868,0.683,0.408,0.284
3,Iceland,4,7.495,1.343,0.914,0.677,0.138,0.353
4,Switzerland,5,7.487,1.420,0.927,0.660,0.357,0.256
...,...,...,...,...,...,...,...,...
151,Yemen,152,3.355,0.442,0.343,0.244,0.064,0.083
152,Tanzania,153,3.303,0.455,0.381,0.481,0.097,0.270
153,South Sudan,154,3.254,0.337,0.177,0.112,0.106,0.224
154,Central African Republic,155,3.083,0.024,0.010,0.305,0.038,0.218
155,Burundi,156,2.905,0.091,0.145,0.065,0.076,0.149

### 2019

In [15]:
df_2019 = d['Resources/2019.csv']
df_2019.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [34]:
new_df_2019 = df_2019[['Country or region', 'Overall rank', 'Score', 'GDP per capita', 'Healthy life expectancy',
                      'Freedom to make life choices', 'Perceptions of corruption', 'Generosity']].copy()
new_df_2018.rename(columns = {'Country or region': "country", 'Overall rank': "happiness rank", 
                             'Score': "happiness score", 'GDP per capita': "GDP",
                             'Healthy life expectancy': "health - life expectancy", 'Freedom to make life choices':"freedom",
                             'Perceptions of corruption': "trust (govt corruption)", 'Generosity': "generosity"}, inplace=True)
new_df_2019

,Country or region,Overall rank,Score,GDP per capita,Healthy life expectancy,Freedom to make life choices,Perceptions of corruption,Generosity
0,Finland,1,7.769,1.340,0.986,0.596,0.393,0.153
1,Denmark,2,7.600,1.383,0.996,0.592,0.410,0.252
2,Norway,3,7.554,1.488,1.028,0.603,0.341,0.271
3,Iceland,4,7.494,1.380,1.026,0.591,0.118,0.354
4,Netherlands,5,7.488,1.396,0.999,0.557,0.298,0.322
...,...,...,...,...,...,...,...,...
151,Rwanda,152,3.334,0.359,0.614,0.555,0.411,0.217
152,Tanzania,153,3.231,0.476,0.499,0.417,0.147,0.276
153,Afghanistan,154,3.203,0.350,0.361,0.000,0.025,0.158
154,Central African Republic,155,3.083,0.026,0.105,0.225,0.035,0.235
155,South Sudan,156,2.853,0.306,0.295,0.010,0.091,0.202

In [18]:
country_count = len(new_df_2019['Country or region'].unique())
country_count

156